language: c
compiler:
  - clang
  - gcc
notifications:
  email:
    - underspell@gmail.com
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libmilter-dev libspf2-dev libspf2-2 opendkim-tools lcov
  - gem install coveralls-lcov
script:
  -  make
  -  make coverage
  - ./run_tests.sh
after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' 'usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info
